services:
  backend:
    build:
      context: ./backend
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      network_server:
        ipv4_address: 172.0.20.2
    volumes:
      - images-data:/app/images:rw
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      network_client:
        ipv4_address: 172.0.22.2
    restart: unless-stopped

  reverse_proxy:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      network_client:
        ipv4_address: 172.0.22.254
      network_server:
        ipv4_address: 172.0.20.254
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email wishira2013.coth@gmail.com -d kunmuay-giffrine.com --agree-tos

networks:
  network_server:
    ipam:
      config:
        - subnet: "172.0.20.0/24"
  network_client:
    ipam:
      config:
        - subnet: "172.0.22.0/24"

volumes:
  images-data:
